version: "3.7"

services:
  node-red:
    build: 
      context: .
      dockerfile: Docker/dockerfile
    container_name: node-red
    restart: always
    env_file:
      - .env
    ports:
      - "1880:1880"
    #network_mode: "host"
    networks:
      - node-red-net
      - default
    volumes:
      - ./node-red-data:/data
      - ./src:/dev/src
      - ./package.json:/dev/package.json

networks:
  node-red-net: